apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-backend-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: blog.local
      http:
        paths:
        # Auth teenus (LISA SEE!)
          - path: /auth/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-srv
                port:
                  number: 5006
          # Posti loomine
          - path: /posts/create
            pathType: Prefix
            backend:
              service:
                name: posts-srv
                port:
                  number: 5000
          # Kommentaaride lisamine
          - path: /posts/
            pathType: Prefix
            backend:
              service:
                name: comments-srv
                port:
                  number: 5001
          # Postituste ja kommentaaride koondvaade
          - path: /posts
            pathType: Prefix
            backend:
              service:
                name: query-srv
                port:
                  number: 5002
